- model:
    model_type: UNet
    kwargs:
      in_channels: 1
      out_channels: 1
      base_filters: 16
      depth: 3

- model:
    model_type: UNet
    kwargs:
      in_channels: 1
      out_channels: 1
      base_filters: 16
      depth: 5

- model:
    model_type: UNet
    kwargs:
      in_channels: 1
      out_channels: 1
      base_filters: 24
      depth: 4

- model:
    model_type: UNet
    kwargs:
      in_channels: 1
      out_channels: 1
      base_filters: 32
      depth: 3

- model:
    model_type: UNet
    kwargs:
      in_channels: 1
      out_channels: 2
      base_filters: 32
      depth: 5

- model:
    model_type: UNet
    kwargs:
      in_channels: 3
      out_channels: 1
      base_filters: 48
      depth: 4

- model:
    model_type: UNet
    kwargs:
      in_channels: 1
      out_channels: 1
      base_filters: 48
      depth: 6

- model:
    model_type: UNet
    kwargs:
      in_channels: 1
      out_channels: 1
      base_filters: 64
      depth: 4

- model:
    model_type: UNet
    kwargs:
      in_channels: 1
      out_channels: 2
      base_filters: 24
      depth: 6

- model:
    model_type: UNet
    kwargs:
      in_channels: 1
      out_channels: 1
      base_filters: 64
      depth: 6

- model:
    model_type: ResUNet
    kwargs:
      in_channels: 1
      out_channels: 1
      base_filters: 16
      depth: 3

- model:
    model_type: ResUNet
    kwargs:
      in_channels: 1
      out_channels: 1
      base_filters: 16
      depth: 4

- model:
    model_type: ResUNet
    kwargs:
      in_channels: 1
      out_channels: 1
      base_filters: 24
      depth: 3

- model:
    model_type: ResUNet
    kwargs:
      in_channels: 1
      out_channels: 2
      base_filters: 24
      depth: 5

- model:
    model_type: ResUNet
    kwargs:
      in_channels: 3
      out_channels: 1
      base_filters: 32
      depth: 4

- model:
    model_type: ResUNet
    kwargs:
      in_channels: 1
      out_channels: 1
      base_filters: 32
      depth: 6

- model:
    model_type: ResUNet
    kwargs:
      in_channels: 1
      out_channels: 1
      base_filters: 48
      depth: 5

- model:
    model_type: ResUNet
    kwargs:
      in_channels: 1
      out_channels: 2
      base_filters: 48
      depth: 4

- model:
    model_type: ResUNet
    kwargs:
      in_channels: 1
      out_channels: 1
      base_filters: 64
      depth: 5

- model:
    model_type: ResUNet
    kwargs:
      in_channels: 1
      out_channels: 1
      base_filters: 64
      depth: 6

- model:
    model_type: ASPPUNet
    kwargs:
      in_channels: 1
      out_channels: 1
      base_filters: 16
      depth: 3

- model:
    model_type: ASPPUNet
    kwargs:
      in_channels: 1
      out_channels: 1
      base_filters: 16
      depth: 4

- model:
    model_type: ASPPUNet
    kwargs:
      in_channels: 1
      out_channels: 2
      base_filters: 24
      depth: 3

- model:
    model_type: ASPPUNet
    kwargs:
      in_channels: 1
      out_channels: 1
      base_filters: 24
      depth: 5

- model:
    model_type: ASPPUNet
    kwargs:
      in_channels: 1
      out_channels: 1
      base_filters: 32
      depth: 4

- model:
    model_type: ASPPUNet
    kwargs:
      in_channels: 1
      out_channels: 1
      base_filters: 48
      depth: 5

- model:
    model_type: ASPPUNet
    kwargs:
      in_channels: 1
      out_channels: 2
      base_filters: 48
      depth: 6

- model:
    model_type: ASPPUNet
    kwargs:
      in_channels: 1
      out_channels: 1
      base_filters: 64
      depth: 4

- model:
    model_type: ASPPUNet
    kwargs:
      in_channels: 1
      out_channels: 1
      base_filters: 64
      depth: 5

- model:
    model_type: ASPPUNet
    kwargs:
      in_channels: 1
      out_channels: 1
      base_filters: 48
      depth: 3

- model:
    model_type: AttentionUNet
    kwargs:
      in_channels: 1
      out_channels: 1
      base_filters: 16
      depth: 3

- model:
    model_type: AttentionUNet
    kwargs:
      in_channels: 1
      out_channels: 1
      base_filters: 16
      depth: 4

- model:
    model_type: AttentionUNet
    kwargs:
      in_channels: 1
      out_channels: 1
      base_filters: 24
      depth: 4

- model:
    model_type: AttentionUNet
    kwargs:
      in_channels: 1
      out_channels: 1
      base_filters: 32
      depth: 3

- model:
    model_type: AttentionUNet
    kwargs:
      in_channels: 1
      out_channels: 1
      base_filters: 32
      depth: 6

- model:
    model_type: AttentionUNet
    kwargs:
      in_channels: 1
      out_channels: 1
      base_filters: 48
      depth: 4

- model:
    model_type: AttentionUNet
    kwargs:
      in_channels: 1
      out_channels: 1
      base_filters: 48
      depth: 5

- model:
    model_type: AttentionUNet
    kwargs:
      in_channels: 1
      out_channels: 1
      base_filters: 64
      depth: 5

- model:
    model_type: AttentionUNet
    kwargs:
      in_channels: 1
      out_channels: 1
      base_filters: 64
      depth: 6

- model:
    model_type: AttentionUNet
    kwargs:
      in_channels: 1
      out_channels: 1
      base_filters: 24
      depth: 6

- model:
    model_type: TransUNet
    kwargs:
      in_channels: 3
      out_channels: 1
      base_filters: 16
      depth: 3

- model:
    model_type: TransUNet
    kwargs:
      in_channels: 3
      out_channels: 1
      base_filters: 16
      depth: 4

- model:
    model_type: TransUNet
    kwargs:
      in_channels: 3
      out_channels: 1
      base_filters: 24
      depth: 4

- model:
    model_type: TransUNet
    kwargs:
      in_channels: 3
      out_channels: 1
      base_filters: 32
      depth: 3

- model:
    model_type: TransUNet
    kwargs:
      in_channels: 3
      out_channels: 1
      base_filters: 32
      depth: 6

- model:
    model_type: TransUNet
    kwargs:
      in_channels: 3
      out_channels: 1
      base_filters: 48
      depth: 4

- model:
    model_type: TransUNet
    kwargs:
      in_channels: 3
      out_channels: 1
      base_filters: 48
      depth: 5

- model:
    model_type: TransUNet
    kwargs:
      in_channels: 3
      out_channels: 1
      base_filters: 64
      depth: 5

- model:
    model_type: TransUNet
    kwargs:
      in_channels: 3
      out_channels: 1
      base_filters: 64
      depth: 6

- model:
    model_type: TransUNet
    kwargs:
      in_channels: 3
      out_channels: 1
      base_filters: 24
      depth: 6

- model:
    model_type: VNet2D
    kwargs:
      in_channels: 1
      out_channels: 1
      base_filters: 16
      depth: 3

- model:
    model_type: VNet2D
    kwargs:
      in_channels: 1
      out_channels: 1
      base_filters: 16
      depth: 4

- model:
    model_type: VNet2D
    kwargs:
      in_channels: 1
      out_channels: 1
      base_filters: 24
      depth: 3

- model:
    model_type: VNet2D
    kwargs:
      in_channels: 1
      out_channels: 1
      base_filters: 24
      depth: 5

- model:
    model_type: VNet2D
    kwargs:
      in_channels: 1
      out_channels: 1
      base_filters: 32
      depth: 4

- model:
    model_type: VNet2D
    kwargs:
      in_channels: 1
      out_channels: 1
      base_filters: 48
      depth: 5

- model:
    model_type: VNet2D
    kwargs:
      in_channels: 1
      out_channels: 1
      base_filters: 64
      depth: 4

- model:
    model_type: VNet2D
    kwargs:
      in_channels: 1
      out_channels: 1
      base_filters: 64
      depth: 5

- model:
    model_type: VNet2D
    kwargs:
      in_channels: 1
      out_channels: 1
      base_filters: 32
      depth: 5

- model:
    model_type: VNet2D
    kwargs:
      in_channels: 1
      out_channels: 1
      base_filters: 16
      depth: 5

- model:
    model_type: ImprovedVNet
    kwargs:
      in_channels: 1
      out_channels: 1
      base_filters: 16
      depth: 3

- model:
    model_type: ImprovedVNet
    kwargs:
      in_channels: 1
      out_channels: 1
      base_filters: 24
      depth: 4

- model:
    model_type: ImprovedVNet
    kwargs:
      in_channels: 1
      out_channels: 1
      base_filters: 32
      depth: 3

- model:
    model_type: ImprovedVNet
    kwargs:
      in_channels: 1
      out_channels: 1
      base_filters: 24
      depth: 5

- model:
    model_type: ImprovedVNet
    kwargs:
      in_channels: 1
      out_channels: 1
      base_filters: 48
      depth: 4

- model:
    model_type: ImprovedVNet
    kwargs:
      in_channels: 1
      out_channels: 1
      base_filters: 48
      depth: 5

- model:
    model_type: ImprovedVNet
    kwargs:
      in_channels: 1
      out_channels: 1
      base_filters: 64
      depth: 3

- model:
    model_type: ImprovedVNet
    kwargs:
      in_channels: 1
      out_channels: 1
      base_filters: 64
      depth: 4

- model:
    model_type: ImprovedVNet
    kwargs:
      in_channels: 1
      out_channels: 1
      base_filters: 32
      depth: 5

- model:
    model_type: ImprovedVNet
    kwargs:
      in_channels: 1
      out_channels: 1
      base_filters: 16
      depth: 5
